name: UrbanUtopiaBuilders
version: '${version}'
main: com.github.oceanoc.urbanutopiabuilders.UrbanUtopiaBuilders
api-version: '1.20'
commands:
  citymenu:
    description: Opens the city menu
    usage: /<command>
  setupcity:
    description: Sets up the addon
    usage: /<command>
  givecityitems:
    description: Gives all city items
    usage: /<command>